import { createSnippetTool } from '@/lib/tools/snippet'

export const asciiTableTool = createSnippetTool({
  id: 'ascii-table',
  name: 'ASCII Table',
  description: 'ASCII character reference: decimal, hex, octal, and names',
  category: 'Snippet',
  items: [
    { key: 'ASCII 0 — NUL', value: '0', description: 'Hex 0x00 · Octal 000 · Null character' },
    { key: 'ASCII 7 — BEL', value: '7', description: 'Hex 0x07 · Octal 007 · Bell (alert)' },
    { key: 'ASCII 8 — BS', value: '8', description: 'Hex 0x08 · Octal 010 · Backspace' },
    { key: 'ASCII 9 — HT', value: '9', description: 'Hex 0x09 · Octal 011 · Horizontal tab (\\t)' },
    { key: 'ASCII 10 — LF', value: '10', description: 'Hex 0x0A · Octal 012 · Line feed (\\n)' },
    { key: 'ASCII 11 — VT', value: '11', description: 'Hex 0x0B · Octal 013 · Vertical tab (\\v)' },
    { key: 'ASCII 12 — FF', value: '12', description: 'Hex 0x0C · Octal 014 · Form feed (\\f)' },
    { key: 'ASCII 13 — CR', value: '13', description: 'Hex 0x0D · Octal 015 · Carriage return (\\r)' },
    { key: 'ASCII 27 — ESC', value: '27', description: 'Hex 0x1B · Octal 033 · Escape' },
    { key: 'ASCII 127 — DEL', value: '127', description: 'Hex 0x7F · Octal 177 · Delete' },
    { key: 'ASCII 32 — Space', value: '32', description: 'Hex 0x20 · Octal 040 · Space' },
    { key: 'ASCII 33 — !', value: '33', description: 'Hex 0x21 · Octal 041 · Exclamation mark' },
    { key: 'ASCII 34 — "', value: '34', description: 'Hex 0x22 · Octal 042 · Double quote' },
    { key: 'ASCII 35 — #', value: '35', description: 'Hex 0x23 · Octal 043 · Number / hash' },
    { key: 'ASCII 36 — $', value: '36', description: 'Hex 0x24 · Octal 044 · Dollar sign' },
    { key: 'ASCII 37 — %', value: '37', description: 'Hex 0x25 · Octal 045 · Percent' },
    { key: 'ASCII 38 — &', value: '38', description: 'Hex 0x26 · Octal 046 · Ampersand' },
    { key: 'ASCII 39 — \'', value: '39', description: 'Hex 0x27 · Octal 047 · Single quote / apostrophe' },
    { key: 'ASCII 40 — (', value: '40', description: 'Hex 0x28 · Octal 050 · Left parenthesis' },
    { key: 'ASCII 41 — )', value: '41', description: 'Hex 0x29 · Octal 051 · Right parenthesis' },
    { key: 'ASCII 42 — *', value: '42', description: 'Hex 0x2A · Octal 052 · Asterisk' },
    { key: 'ASCII 43 — +', value: '43', description: 'Hex 0x2B · Octal 053 · Plus sign' },
    { key: 'ASCII 44 — ,', value: '44', description: 'Hex 0x2C · Octal 054 · Comma' },
    { key: 'ASCII 45 — -', value: '45', description: 'Hex 0x2D · Octal 055 · Hyphen / minus' },
    { key: 'ASCII 46 — .', value: '46', description: 'Hex 0x2E · Octal 056 · Period / dot' },
    { key: 'ASCII 47 — /', value: '47', description: 'Hex 0x2F · Octal 057 · Slash' },
    { key: 'ASCII 48-57 — Digits', value: '48-57', description: 'Hex 0x30-0x39 · Digits 0 through 9' },
    { key: 'ASCII 58 — :', value: '58', description: 'Hex 0x3A · Octal 072 · Colon' },
    { key: 'ASCII 59 — ;', value: '59', description: 'Hex 0x3B · Octal 073 · Semicolon' },
    { key: 'ASCII 60 — <', value: '60', description: 'Hex 0x3C · Octal 074 · Less than' },
    { key: 'ASCII 61 — =', value: '61', description: 'Hex 0x3D · Octal 075 · Equals sign' },
    { key: 'ASCII 62 — >', value: '62', description: 'Hex 0x3E · Octal 076 · Greater than' },
    { key: 'ASCII 63 — ?', value: '63', description: 'Hex 0x3F · Octal 077 · Question mark' },
    { key: 'ASCII 64 — @', value: '64', description: 'Hex 0x40 · Octal 100 · At sign' },
    { key: 'ASCII 65-90 — A-Z', value: '65-90', description: 'Hex 0x41-0x5A · Uppercase letters' },
    { key: 'ASCII 91 — [', value: '91', description: 'Hex 0x5B · Octal 133 · Left bracket' },
    { key: 'ASCII 92 — \\', value: '92', description: 'Hex 0x5C · Octal 134 · Backslash' },
    { key: 'ASCII 93 — ]', value: '93', description: 'Hex 0x5D · Octal 135 · Right bracket' },
    { key: 'ASCII 94 — ^', value: '94', description: 'Hex 0x5E · Octal 136 · Caret' },
    { key: 'ASCII 95 — _', value: '95', description: 'Hex 0x5F · Octal 137 · Underscore' },
    { key: 'ASCII 96 — `', value: '96', description: 'Hex 0x60 · Octal 140 · Backtick / grave' },
    { key: 'ASCII 97-122 — a-z', value: '97-122', description: 'Hex 0x61-0x7A · Lowercase letters' },
    { key: 'ASCII 123 — {', value: '123', description: 'Hex 0x7B · Octal 173 · Left brace' },
    { key: 'ASCII 124 — |', value: '124', description: 'Hex 0x7C · Octal 174 · Pipe / vertical bar' },
    { key: 'ASCII 125 — }', value: '125', description: 'Hex 0x7D · Octal 175 · Right brace' },
    { key: 'ASCII 126 — ~', value: '126', description: 'Hex 0x7E · Octal 176 · Tilde' },
  ],
})
