import { createSnippetTool } from '@/lib/tools/snippet'

export const dockerTool = createSnippetTool({
  id: 'docker',
  name: 'Docker Snippets',
  description: 'Docker and Docker Compose commands for containers, images, volumes, and cleanup',
  category: 'Snippet',
  items: [
    { key: 'docker - run detached', value: 'docker run -d --name <name> <image>', description: 'Run a container in the background' },
    { key: 'docker - run interactive', value: 'docker run -it <image> sh', description: 'Run a container and open a shell' },
    { key: 'docker - run with port', value: 'docker run -p 8080:80 <image>', description: 'Map host port 8080 to container port 80' },
    { key: 'docker - run with volume', value: 'docker run -v $(pwd):/app <image>', description: 'Mount the current directory into the container' },
    { key: 'docker - run with env', value: 'docker run -e KEY=value <image>', description: 'Pass an environment variable' },
    { key: 'docker - run with env file', value: 'docker run --env-file .env <image>', description: 'Load environment variables from a file' },
    { key: 'docker - list running', value: 'docker ps', description: 'List running containers' },
    { key: 'docker - list all', value: 'docker ps -a', description: 'List all containers (incl. stopped)' },
    { key: 'docker - list images', value: 'docker images', description: 'List local images' },
    { key: 'docker - remove image', value: 'docker rmi <image>', description: 'Remove a local image' },
    { key: 'docker - remove dangling images', value: 'docker image prune -f', description: 'Remove untagged dangling images' },
    { key: 'docker - remove unused images', value: 'docker image prune -a', description: 'Remove all images not used by a container' },
    { key: 'docker - exec into container', value: 'docker exec -it <name> sh', description: 'Open a shell in a running container' },
    { key: 'docker - exec as root', value: 'docker exec -u root -it <name> sh', description: 'Open a shell as root in a running container' },
    { key: 'docker - follow logs', value: 'docker logs -f <name>', description: 'Stream container logs live' },
    { key: 'docker - tail n logs', value: 'docker logs --tail 100 <name>', description: 'Show the last 100 log lines' },
    { key: 'docker - logs since time', value: 'docker logs --since 30m <name>', description: 'Show logs from the last 30 minutes' },
    { key: 'docker - logs with timestamps', value: 'docker logs -t <name>', description: 'Show logs with UTC timestamps' },
    { key: 'docker - build image', value: 'docker build -t <name> .', description: 'Build an image from the current Dockerfile' },
    { key: 'docker - build no cache', value: 'docker build --no-cache -t <name> .', description: 'Build without using the layer cache' },
    { key: 'docker - compose up', value: 'docker compose up -d', description: 'Start compose services in the background' },
    { key: 'docker - compose up rebuild', value: 'docker compose up -d --build', description: 'Rebuild images then start services' },
    { key: 'docker - compose down', value: 'docker compose down', description: 'Stop and remove compose services' },
    { key: 'docker - compose logs', value: 'docker compose logs -f', description: 'Follow logs of all compose services' },
    { key: 'docker - compose exec', value: 'docker compose exec <service> sh', description: 'Open a shell in a compose service' },
    { key: 'docker - compose restart', value: 'docker compose restart <service>', description: 'Restart a single compose service' },
    { key: 'docker - list volumes', value: 'docker volume ls', description: 'List all Docker volumes' },
    { key: 'docker - remove volumes', value: 'docker volume prune', description: 'Remove volumes not used by any container' },
    { key: 'docker - list networks', value: 'docker network ls', description: 'List all Docker networks' },
    { key: 'docker - inspect network', value: 'docker network inspect <name>', description: 'Show details of a network' },
    { key: 'docker - remove stopped containers', value: 'docker container prune', description: 'Remove all stopped containers' },
    { key: 'docker - system prune', value: 'docker system prune -a', description: 'Remove all unused containers, images, networks, volumes' },
    { key: 'docker - stats', value: 'docker stats', description: 'Live resource usage for running containers' },
    { key: 'docker - top processes', value: 'docker top <name>', description: 'Show running processes inside a container' },
  ],
})
