import { createSnippetTool } from '@/lib/tools/snippet'

export const gitTool = createSnippetTool({
  id: 'git',
  name: 'Git Snippets',
  description: 'Git commands for branching, committing, stashing, merging, and fixing tracking',
  category: 'Snippet',
  items: [
    { key: 'git - clone repo', value: 'git clone <url>', description: 'Clone a remote repository' },
    { key: 'git - shallow clone', value: 'git clone --depth 1 <url>', description: 'Clone only the latest commit (faster)' },
    { key: 'git - clone specific branch', value: 'git clone -b <branch> <url>', description: 'Clone a single branch' },
    { key: 'git - set user name', value: 'git config user.name "Name"', description: 'Set local git user name' },
    { key: 'git - set user email', value: 'git config user.email "email"', description: 'Set local git user email' },
    { key: 'git - default branch main', value: 'git config --global init.defaultBranch main', description: 'Set default branch name to main' },
    { key: 'git - list branches', value: 'git branch', description: 'List local branches' },
    { key: 'git - list all branches', value: 'git branch -a', description: 'List local and remote branches' },
    { key: 'git - create + switch branch', value: 'git switch -c <branch>', description: 'Create a new branch and switch to it' },
    { key: 'git - switch branch', value: 'git switch <branch>', description: 'Switch to an existing branch' },
    { key: 'git - delete local branch', value: 'git branch -d <branch>', description: 'Delete a merged local branch' },
    { key: 'git - force delete local branch', value: 'git branch -D <branch>', description: 'Force delete a local branch (even if unmerged)' },
    { key: 'git - delete remote branch', value: 'git push origin --delete <branch>', description: 'Delete a branch on the remote' },
    { key: 'git - branches merged into main', value: 'git branch --merged main', description: 'List branches already merged into main' },
    { key: 'git - stage all', value: 'git add -A', description: 'Stage all changes (incl. deletions)' },
    { key: 'git - commit', value: 'git commit -m "message"', description: 'Commit staged changes' },
    { key: 'git - stage tracked + commit', value: 'git commit -am "message"', description: 'Stage tracked files and commit in one step' },
    { key: 'git - amend message', value: 'git commit --amend -m "message"', description: 'Change the last commit message' },
    { key: 'git - amend with new changes', value: 'git commit --amend --no-edit', description: 'Add changes to last commit, keep message' },
    { key: 'git - undo last commit (keep staged)', value: 'git reset --soft HEAD~1', description: 'Undo commit, keep changes staged' },
    { key: 'git - undo last commit (unstage)', value: 'git reset HEAD~1', description: 'Undo commit, keep changes unstaged' },
    { key: 'git - undo last commit (discard)', value: 'git reset --hard HEAD~1', description: 'Undo commit and discard all changes' },
    { key: 'git - stash save named', value: 'git stash push -m "wip"', description: 'Stash changes with a label' },
    { key: 'git - stash list', value: 'git stash list', description: 'List all stashes' },
    { key: 'git - stash pop', value: 'git stash pop', description: 'Apply and remove the latest stash' },
    { key: 'git - stash apply (keep)', value: 'git stash apply', description: 'Apply latest stash without removing it' },
    { key: 'git - stash drop', value: 'git stash drop stash@{0}', description: 'Delete a specific stash' },
    { key: 'git - log oneline', value: 'git log --oneline', description: 'Show compact commit history' },
    { key: 'git - log graph', value: 'git log --oneline --graph --all', description: 'Visual branch/commit graph' },
    { key: 'git - last n commits', value: 'git log -n 5', description: 'Show the last 5 commits' },
    { key: 'git - search commit messages', value: 'git log --grep="fix"', description: 'Find commits whose message matches a pattern' },
    { key: 'git - list remotes', value: 'git remote -v', description: 'Show remote repositories and URLs' },
    { key: 'git - change remote url', value: 'git remote set-url origin <url>', description: 'Update the origin remote URL' },
    { key: 'git - merge branch', value: 'git merge <branch>', description: 'Merge a branch into the current branch' },
    { key: 'git - abort merge', value: 'git merge --abort', description: 'Cancel an in-progress merge' },
    { key: 'git - rebase interactive', value: 'git rebase -i HEAD~3', description: 'Squash/reword the last 3 commits' },
    { key: 'git - abort rebase', value: 'git rebase --abort', description: 'Cancel an in-progress rebase' },
    { key: 'git - create tag', value: 'git tag v1.0.0', description: 'Create a lightweight tag' },
    { key: 'git - annotated tag', value: 'git tag -a v1.0.0 -m "release"', description: 'Create a tag with a message' },
    { key: 'git - push tags', value: 'git push --tags', description: 'Push all tags to the remote' },
    { key: 'git - delete tag remote', value: 'git push origin --delete v1.0.0', description: 'Delete a tag on the remote' },
    { key: 'git - restore file', value: 'git restore <file>', description: 'Discard uncommitted changes in a file' },
    { key: 'git - unstage file', value: 'git restore --staged <file>', description: 'Unstage a file without discarding changes' },
    { key: 'git - push set upstream', value: 'git push -u origin <branch>', description: 'Push and set upstream tracking branch' },
    { key: 'git - force push safely', value: 'git push --force-with-lease', description: 'Force push, aborts if remote has new commits' },
    { key: 'git - remove gitignore cache', value: 'git rm -r --cached . && git add . && git commit -m "remove ignored files"', description: 'Untrack files now listed in .gitignore' },
    { key: 'git - untrack single file', value: 'git rm --cached <file>', description: 'Stop tracking one file without deleting it locally' },
  ],
})
