import { createSnippetTool } from '@/lib/tools/snippet'

export const htmlEntitiesTool = createSnippetTool({
  id: 'html-entities',
  name: 'HTML Entities',
  description: 'Common HTML character entities (named + decimal code) for escaping content',
  category: 'Snippet',
  items: [
    { key: 'Ampersand', value: '&amp;', description: '& — decimal &#38;' },
    { key: 'Less than', value: '&lt;', description: '< — decimal &#60;' },
    { key: 'Greater than', value: '&gt;', description: '> — decimal &#62;' },
    { key: 'Non-breaking space', value: '&nbsp;', description: 'non-breaking space — decimal &#160;' },
    { key: 'Double quote', value: '&quot;', description: '" — decimal &#34;' },
    { key: 'Single quote', value: '&apos;', description: "' — decimal &#39;" },
    { key: 'Copyright', value: '&copy;', description: '© — decimal &#169;' },
    { key: 'Registered', value: '&reg;', description: '® — decimal &#174;' },
    { key: 'Trademark', value: '&trade;', description: '™ — decimal &#8482;' },
    { key: 'Degree', value: '&deg;', description: '° — decimal &#176;' },
    { key: 'Plus-minus', value: '&plusmn;', description: '± — decimal &#177;' },
    { key: 'Times (multiply)', value: '&times;', description: '× — decimal &#215;' },
    { key: 'Divide', value: '&divide;', description: '÷ — decimal &#247;' },
    { key: 'Euro', value: '&euro;', description: '€ — decimal &#8364;' },
    { key: 'Pound', value: '&pound;', description: '£ — decimal &#163;' },
    { key: 'Yen', value: '&yen;', description: '¥ — decimal &#165;' },
    { key: 'Cent', value: '&cent;', description: '¢ — decimal &#162;' },
    { key: 'Em dash', value: '&mdash;', description: '— — decimal &#8212;' },
    { key: 'En dash', value: '&ndash;', description: '– — decimal &#8211;' },
    { key: 'Horizontal ellipsis', value: '&hellip;', description: '… — decimal &#8230;' },
    { key: 'Left angle quote', value: '&laquo;', description: '« — decimal &#171;' },
    { key: 'Right angle quote', value: '&raquo;', description: '» — decimal &#187;' },
    { key: 'Left arrow', value: '&larr;', description: '← — decimal &#8592;' },
    { key: 'Right arrow', value: '&rarr;', description: '→ — decimal &#8594;' },
    { key: 'Up arrow', value: '&uarr;', description: '↑ — decimal &#8593;' },
    { key: 'Down arrow', value: '&darr;', description: '↓ — decimal &#8595;' },
    { key: 'Bullet', value: '&bull;', description: '• — decimal &#8226;' },
    { key: 'Check mark', value: '&check;', description: '✓ — decimal &#10003;' },
    { key: 'Section sign', value: '&sect;', description: '§ — decimal &#167;' },
    { key: 'Paragraph sign', value: '&para;', description: '¶ — decimal &#182;' },
    { key: 'Micro sign', value: '&micro;', description: 'µ — decimal &#181;' },
    { key: 'Pilcrow (newline hint)', value: '&#10;', description: 'Line feed character — for line breaks in attributes' },
  ],
})
