import { createSnippetTool } from '@/lib/tools/snippet'

export const kubectlTool = createSnippetTool({
  id: 'kubectl',
  name: 'kubectl Snippets',
  description: 'Kubernetes commands for pods, deployments, logs, scaling, and context management',
  category: 'Snippet',
  items: [
    { key: 'kubectl - get pods', value: 'kubectl get pods', description: 'List pods in the current namespace' },
    { key: 'kubectl - get pods all namespaces', value: 'kubectl get pods -A', description: 'List pods across all namespaces' },
    { key: 'kubectl - get pods wide', value: 'kubectl get pods -o wide', description: 'List pods with node and IP details' },
    { key: 'kubectl - get deployments', value: 'kubectl get deployments', description: 'List deployments in current namespace' },
    { key: 'kubectl - get services', value: 'kubectl get svc', description: 'List services in current namespace' },
    { key: 'kubectl - get nodes', value: 'kubectl get nodes', description: 'List cluster nodes' },
    { key: 'kubectl - get namespaces', value: 'kubectl get ns', description: 'List all namespaces' },
    { key: 'kubectl - describe pod', value: 'kubectl describe pod <name>', description: 'Show detailed info about a pod' },
    { key: 'kubectl - logs follow', value: 'kubectl logs -f <pod>', description: 'Stream pod logs live' },
    { key: 'kubectl - logs previous', value: 'kubectl logs -p <pod>', description: 'Show logs from the previous (crashed) container' },
    { key: 'kubectl - logs tail n', value: 'kubectl logs --tail=100 <pod>', description: 'Show the last 100 log lines' },
    { key: 'kubectl - logs multi-container', value: 'kubectl logs -f <pod> -c <container>', description: 'Stream logs from a specific container' },
    { key: 'kubectl - exec into pod', value: 'kubectl exec -it <pod> -- sh', description: 'Open a shell inside a pod' },
    { key: 'kubectl - port forward', value: 'kubectl port-forward <pod> 8080:80', description: 'Forward local 8080 to pod port 80' },
    { key: 'kubectl - port forward service', value: 'kubectl port-forward svc/<name> 8080:80', description: 'Forward local 8080 to a service port' },
    { key: 'kubectl - apply file', value: 'kubectl apply -f file.yaml', description: 'Apply a manifest (create or update)' },
    { key: 'kubectl - delete file', value: 'kubectl delete -f file.yaml', description: 'Delete resources defined in a manifest' },
    { key: 'kubectl - scale deployment', value: 'kubectl scale deploy <name> --replicas=3', description: 'Scale a deployment to 3 replicas' },
    { key: 'kubectl - rollout status', value: 'kubectl rollout status deploy/<name>', description: 'Watch a rollout until it completes' },
    { key: 'kubectl - rollout undo', value: 'kubectl rollout undo deploy/<name>', description: 'Roll back to the previous revision' },
    { key: 'kubectl - rollout history', value: 'kubectl rollout history deploy/<name>', description: 'Show revision history of a deployment' },
    { key: 'kubectl - set namespace', value: 'kubectl config set-context --current --namespace=<ns>', description: 'Set the default namespace for current context' },
    { key: 'kubectl - get contexts', value: 'kubectl config get-contexts', description: 'List all configured contexts' },
    { key: 'kubectl - use context', value: 'kubectl config use-context <name>', description: 'Switch the active context' },
    { key: 'kubectl - top pods', value: 'kubectl top pods', description: 'Show CPU/memory usage per pod (needs metrics-server)' },
    { key: 'kubectl - top nodes', value: 'kubectl top nodes', description: 'Show CPU/memory usage per node' },
    { key: 'kubectl - explain resource', value: 'kubectl explain pod.spec.containers', description: 'Show the schema for a resource field' },
  ],
})
