import { createSnippetTool } from '@/lib/tools/snippet'

export const mimeTypesTool = createSnippetTool({
  id: 'mime-types',
  name: 'MIME Types',
  description: 'Common MIME (Content-Type) values mapped to file extensions',
  category: 'Snippet',
  items: [
    { key: 'JSON', value: 'application/json', description: 'Used for .json files and API payloads' },
    { key: 'XML', value: 'application/xml', description: 'Used for .xml files' },
    { key: 'YAML', value: 'application/yaml', description: 'Used for .yaml / .yml files' },
    { key: 'TOML', value: 'application/toml', description: 'Used for .toml files' },
    { key: 'HTML', value: 'text/html', description: 'Used for .html / .htm files' },
    { key: 'CSS', value: 'text/css', description: 'Used for .css files' },
    { key: 'JavaScript', value: 'text/javascript', description: 'Used for .js / .mjs files' },
    { key: 'TypeScript', value: 'application/typescript', description: 'Used for .ts files' },
    { key: 'Plain text', value: 'text/plain', description: 'Used for .txt files' },
    { key: 'CSV', value: 'text/csv', description: 'Used for .csv files' },
    { key: 'Markdown', value: 'text/markdown', description: 'Used for .md files' },
    { key: 'Shell script', value: 'text/x-shellscript', description: 'Used for .sh / .bash files' },
    { key: 'PDF', value: 'application/pdf', description: 'Used for .pdf documents' },
    { key: 'ZIP archive', value: 'application/zip', description: 'Used for .zip files' },
    { key: 'Gzip', value: 'application/gzip', description: 'Used for .gz / .gzip files' },
    { key: 'Tar archive', value: 'application/x-tar', description: 'Used for .tar files' },
    { key: '7-Zip', value: 'application/x-7z-compressed', description: 'Used for .7z files' },
    { key: 'RAR', value: 'application/x-rar-compressed', description: 'Used for .rar files' },
    { key: 'Binary stream', value: 'application/octet-stream', description: 'Generic binary / unknown type' },
    { key: 'WebAssembly', value: 'application/wasm', description: 'Used for .wasm files' },
    { key: 'PNG image', value: 'image/png', description: 'Used for .png files' },
    { key: 'JPEG image', value: 'image/jpeg', description: 'Used for .jpg / .jpeg files' },
    { key: 'GIF image', value: 'image/gif', description: 'Used for .gif files' },
    { key: 'SVG image', value: 'image/svg+xml', description: 'Used for .svg files' },
    { key: 'WebP image', value: 'image/webp', description: 'Used for .webp files' },
    { key: 'AVIF image', value: 'image/avif', description: 'Used for .avif files' },
    { key: 'Icon', value: 'image/x-icon', description: 'Used for .ico files' },
    { key: 'MP3 audio', value: 'audio/mpeg', description: 'Used for .mp3 files' },
    { key: 'WAV audio', value: 'audio/wav', description: 'Used for .wav files' },
    { key: 'OGG audio', value: 'audio/ogg', description: 'Used for .ogg / .oga files' },
    { key: 'MP4 video', value: 'video/mp4', description: 'Used for .mp4 files' },
    { key: 'WebM video', value: 'video/webm', description: 'Used for .webm files' },
    { key: 'MPEG video', value: 'video/mpeg', description: 'Used for .mpeg / .mpg files' },
    { key: 'WOFF font', value: 'font/woff', description: 'Used for .woff files' },
    { key: 'WOFF2 font', value: 'font/woff2', description: 'Used for .woff2 files' },
    { key: 'TrueType font', value: 'font/ttf', description: 'Used for .ttf files' },
    { key: 'OpenType font', value: 'font/otf', description: 'Used for .otf files' },
    { key: 'Word (docx)', value: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', description: 'Used for .docx files' },
    { key: 'Excel (xlsx)', value: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', description: 'Used for .xlsx files' },
    { key: 'PowerPoint (pptx)', value: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', description: 'Used for .pptx files' },
    { key: 'Form data', value: 'multipart/form-data', description: 'Used for file upload forms' },
    { key: 'URL-encoded form', value: 'application/x-www-form-urlencoded', description: 'Used for HTML form POST bodies' },
  ],
})
