import { createSnippetTool } from '@/lib/tools/snippet'

export const postgresqlTool = createSnippetTool({
  id: 'postgresql',
  name: 'PostgreSQL Snippets',
  description: 'Common PostgreSQL queries - JOIN, GROUP BY, aggregate functions',
  category: 'Snippet',
  items: [
    { key: 'SELECT with JOIN', value: 'SELECT u.name, o.total\nFROM users u\nINNER JOIN orders o ON u.id = o.user_id', description: 'Inner join users and orders' },
    { key: 'LEFT JOIN', value: 'SELECT u.name, o.total\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id', description: 'Left join including nulls' },
    { key: 'GROUP BY + SUM', value: 'SELECT user_id, SUM(total) AS total_sum\nFROM orders\nGROUP BY user_id\nHAVING SUM(total) > 100', description: 'Group with aggregate and filter' },
    { key: 'GROUP BY + COUNT', value: 'SELECT category, COUNT(*) AS count\nFROM products\nGROUP BY category\nORDER BY count DESC', description: 'Count items per category' },
    { key: 'Subquery in WHERE', value: 'SELECT name\nFROM users\nWHERE id IN (\n  SELECT user_id\n  FROM orders\n  WHERE total > 50\n)', description: 'Subquery to filter results' },
    { key: 'COALESCE null handling', value: 'SELECT name, COALESCE(phone, \'N/A\') AS phone\nFROM users', description: 'Handle null values' },
    { key: 'CASE when conditional', value: 'SELECT name,\n  CASE\n    WHEN total > 1000 THEN \'High\'\n    WHEN total > 500 THEN \'Medium\'\n    ELSE \'Low\'\n  END AS tier\nFROM orders', description: 'Conditional logic in select' },
    { key: 'DATE truncation', value: 'SELECT DATE_TRUNC(\'month\', created_at) AS month, SUM(total)\nFROM orders\nGROUP BY DATE_TRUNC(\'month\', created_at)\nORDER BY month', description: 'Group by month' },
    { key: 'Window function - ROW_NUMBER', value: 'SELECT name, total,\n  ROW_NUMBER() OVER (PARTITION BY status ORDER BY total DESC) AS rank\nFROM orders', description: 'Rank within groups' },
    { key: 'Common Table Expression (CTE)', value: 'WITH active_users AS (\n  SELECT * FROM users WHERE active = true\n)\nSELECT u.name, o.total\nFROM active_users u\nJOIN orders o ON u.id = o.user_id', description: 'Using WITH clause' },
    { key: 'INSERT with RETURNING', value: 'INSERT INTO users (name, email)\nVALUES (\'John\', \'john@example.com\')\nRETURNING id, name', description: 'Insert and get generated ID' },
    { key: 'UPDATE with RETURNING', value: 'UPDATE users\nSET active = false\nWHERE last_login < NOW() - INTERVAL \'30 days\'\nRETURNING id, name', description: 'Update and get affected rows' },
    { key: 'UPSERT (ON CONFLICT)', value: 'INSERT INTO users (id, name, email)\nVALUES (1, \'John\', \'john@example.com\')\nON CONFLICT (id) DO UPDATE\nSET name = EXCLUDED.name', description: 'Insert or update on conflict' },
    { key: 'EXPLAIN ANALYZE', value: 'EXPLAIN ANALYZE\nSELECT * FROM orders\nWHERE user_id = 1', description: 'Query execution plan' },
    { key: 'Generate series', value: 'SELECT *\nFROM generate_series(\n  NOW() - INTERVAL \'7 days\',\n  NOW(),\n  INTERVAL \'1 day\'\n)', description: 'Generate date sequence' },
    { key: 'WHERE BETWEEN dates', value: "SELECT *\nFROM orders\nWHERE created_at BETWEEN '2024-01-01' AND '2024-01-31'", description: 'Filter date range (inclusive)' },
    { key: 'WHERE >= and <', value: "SELECT *\nFROM orders\nWHERE created_at >= '2024-01-01'\n  AND created_at < '2024-02-01'", description: 'Date range with exclusive end' },
    { key: 'WHERE date on specific day', value: "SELECT *\nFROM orders\nWHERE DATE(created_at) = '2024-01-15'", description: 'Filter by exact date' },
    { key: 'WHERE date in (today, yesterday)', value: 'SELECT *\nFROM orders\nWHERE created_at >= CURRENT_DATE\n  AND created_at < CURRENT_DATE + 1', description: 'Filter today only' },
    { key: 'WHERE this week', value: 'SELECT *\nFROM orders\nWHERE created_at >= DATE_TRUNC(\'week\', CURRENT_DATE)', description: 'Filter current week' },
    { key: 'WHERE this month', value: 'SELECT *\nFROM orders\nWHERE created_at >= DATE_TRUNC(\'month\', CURRENT_DATE)', description: 'Filter current month' },
    { key: 'WHERE last N days', value: 'SELECT *\nFROM orders\nWHERE created_at >= NOW() - INTERVAL \'30 days\'', description: 'Filter last 30 days' },
    { key: 'WHERE time part extraction', value: "SELECT *\nFROM orders\nWHERE EXTRACT(YEAR FROM created_at) = 2024\n  AND EXTRACT(MONTH FROM created_at) = 1", description: 'Filter by year and month' },
    { key: 'Date arithmetic', value: "SELECT NOW() - INTERVAL '7 days' AS week_ago,\n       CURRENT_DATE + 1 AS tomorrow,\n       AGE(CURRENT_DATE, '2024-01-01') AS days_old", description: 'Date math operations' },
    { key: 'TO_CHAR formatting', value: "SELECT name,\n       TO_CHAR(created_at, 'YYYY-MM-DD') AS date,\n       TO_CHAR(created_at, 'HH24:MI:SS') AS time,\n       TO_CHAR(created_at, 'Dy') AS weekday\nFROM orders", description: 'Format date to string' },
  ],
})
