import { createSnippetTool } from '@/lib/tools/snippet'

export const regexTool = createSnippetTool({
  id: 'regex',
  name: 'Regex Patterns',
  description: 'Common regex patterns for matching text, numbers, emails, and more',
  category: 'Snippet',
  items: [
    { key: 'All Digits', value: '\\d+', description: 'Match one or more digits' },
    { key: 'All Letters', value: '[a-zA-Z]+', description: 'Match one or more letters' },
    { key: 'Alphanumeric', value: '[a-zA-Z0-9]+', description: 'Match letters and numbers' },
    { key: 'Lowercase Letters', value: '[a-z]+', description: 'Match lowercase letters only' },
    { key: 'Uppercase Letters', value: '[A-Z]+', description: 'Match uppercase letters only' },
    { key: 'Whitespace', value: '\\s+', description: 'Match one or more whitespace characters' },
    { key: 'Non-Whitespace', value: '\\S+', description: 'Match one or more non-whitespace characters' },
    { key: 'Word Characters', value: '\\w+', description: 'Match word characters (letters, digits, underscore)' },
    { key: 'Decimal Number', value: '\\d+\\.\\d+', description: 'Match decimal numbers like 3.14' },
    { key: 'Integer', value: '-?\\d+', description: 'Match positive or negative integers' },
    { key: 'Positive Integer', value: '\\d+', description: 'Match positive integers only' },
    { key: 'Negative Integer', value: '-\\d+', description: 'Match negative integers only' },
    { key: 'Hex Color', value: '#[0-9A-Fa-f]{6}', description: 'Match hex color codes like #FF5733' },
    { key: 'Email Address', value: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}', description: 'Match email addresses' },
    { key: 'URL', value: 'https?://[^\\s]+', description: 'Match HTTP/HTTPS URLs' },
    { key: 'Phone (US)', value: '\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}', description: 'Match US phone numbers' },
    { key: 'Date (YYYY-MM-DD)', value: '\\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])', description: 'Match ISO date format' },
    { key: 'Date (DD/MM/YYYY)', value: '(?:0[1-9]|[12]\\d|3[01])/(?:0[1-9]|1[0-2])/\\d{4}', description: 'Match European date format' },
    { key: 'Time (24h)', value: '(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d)?', description: 'Match 24-hour time format' },
    { key: 'IPv4 Address', value: '(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)\\.(?:25[0-5]|2[0-4]\\d|[01]?\\d\\d?)', description: 'Match IPv4 addresses' },
    { key: 'MAC Address', value: '(?:[0-9A-Fa-f]{2}:){5}[0-9A-Fa-f]{2}', description: 'Match MAC addresses' },
    { key: 'Credit Card', value: '(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13})', description: 'Match Visa, MasterCard, Amex' },
    { key: 'HTML Tag', value: '<([a-z]+)([^<]+)*(?:>(.*)<\\/\\1>|\\s+\\/>)', description: 'Match HTML tags' },
    { key: 'Slug', value: '[a-z0-9]+(?:-[a-z0-9]+)*', description: 'Match URL-friendly slugs' },
    { key: 'Username', value: '[a-zA-Z0-9_-]{3,16}', description: 'Match usernames (3-16 chars)' },
    { key: 'Password (Strong)', value: '(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}', description: 'Match strong passwords' },
    { key: 'JSON String', value: '"(?:[^"\\\\]|\\\\.)*"', description: 'Match JSON string values' },
    { key: 'UUID', value: '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', description: 'Match UUIDs' },
    { key: 'Semver', value: '\\d+\\.\\d+\\.\\d+(?:-[\\w.]+)?', description: 'Match semantic versioning' },
    { key: 'File Extension', value: '\\.[a-zA-Z0-9]+$', description: 'Match file extensions' },
    { key: 'Chinese Characters', value: '[\\u4e00-\\u9fff]+', description: 'Match Chinese characters' },
    { key: 'Thai Characters', value: '[\\u0e00-\\u0e7f]+', description: 'Match Thai characters' },
    { key: 'Korean Characters', value: '[\\ac00-\\ud7af]+', description: 'Match Korean characters (Hangul)' },
    { key: 'Japanese Hiragana', value: '[\\u3040-\\u309f]+', description: 'Match Japanese Hiragana' },
    { key: 'Japanese Katakana', value: '[\\u30a0-\\u30ff]+', description: 'Match Japanese Katakana' },
    { key: 'Emoji', value: '(?:[\\u2700-\\u27bf]|(?:\\ud83c[\\ud000-\\udfff]){2}|(?:\\ud83d[\\udc00-\\ude4f]){2}|[\\ud800-\\udbff][\\udc00-\\udfff])', description: 'Match emoji characters' },
    { key: 'Empty Line', value: '^\\s*$', description: 'Match empty or whitespace-only lines' },
    { key: 'Start of Line', value: '^', description: 'Match start of line anchor' },
    { key: 'End of Line', value: '$', description: 'Match end of line anchor' },
    { key: 'Word Boundary', value: '\\b', description: 'Match word boundary' },
  ],
})
