import { createSnippetTool } from '@/lib/tools/snippet'

export const shellTool = createSnippetTool({
  id: 'shell',
  name: 'Shell Snippets',
  description: 'Common shell commands for grep, awk, sed, find, curl, and jq',
  category: 'Snippet',
  items: [
    { key: 'grep - "error" in file', value: 'grep "error" app.log', description: 'Find lines containing "error"' },
    { key: 'grep - case insensitive', value: 'grep -i "error" app.log', description: 'Find "error" ignoring case' },
    { key: 'grep - with line numbers', value: 'grep -n "error" app.log', description: 'Find + show line numbers' },
    { key: 'grep - recursive in all .log', value: 'grep -r "failed" /var/log/*.log', description: 'Search recursively in all .log files' },
    { key: 'grep - invert (NOT)', value: 'grep -v "success" app.log', description: 'Find lines NOT containing "success"' },
    { key: 'grep - lines starting with WARN', value: 'grep "^WARN" app.log', description: 'Find lines that start with "WARN"' },
    { key: 'grep - multiple patterns (OR)', value: 'grep -E "error|warning|failed" app.log', description: 'Find lines with error OR warning OR failed' },
    { key: 'awk - print columns 1 & 3', value: "awk '{print $1, $3}' data.txt", description: 'Print column 1 and 3 separated by space' },
    { key: 'awk - print last column', value: "awk '{print $NF}' data.txt", description: 'Print the last column' },
    { key: 'awk - filter column > value', value: "awk '$1 > 100 {print $0}' data.txt", description: 'Print lines where column 1 > 100' },
    { key: 'awk - sum column', value: "awk '{sum+=$2} END {print sum}' data.txt", description: 'Sum all values in column 2' },
    { key: 'awk - count lines', value: "awk 'END {print NR}' data.txt", description: 'Print total number of lines' },
    { key: 'awk - replace delimiter', value: 'awk -F: \'{print $1","$2}\' data.txt', description: 'Replace : with , between column 1 & 2' },
    { key: 'find - by name', value: 'find . -name "config.*"', description: 'Find files named "config.*"' },
    { key: 'find - modified in 7 days', value: 'find . -mtime -7', description: 'Find files modified within 7 days' },
    { key: 'find - larger than 100MB', value: 'find . -size +100M', description: 'Find files larger than 100MB' },
    { key: 'find - exclude .git', value: 'find . -not -path "*/.git/*"', description: 'Find excluding .git directory' },
    { key: 'find - delete .tmp files', value: 'find . -name "*.tmp" -delete', description: 'Delete all .tmp files' },
    { key: 'find - exec on results', value: 'find . -name "*.log" -exec rm {} \\;', description: 'Run rm on each .log file found' },
    { key: 'sed - find & replace all', value: "sed 's/foo/bar/g' file.txt", description: 'Replace all "foo" with "bar"' },
    { key: 'sed - delete lines with pattern', value: "sed '/pattern/d' file.txt", description: 'Delete lines containing "pattern"' },
    { key: 'sed - insert line after', value: "sed -i '3a\\New line' file.txt", description: 'Insert "New line" after line 3' },
    { key: 'xargs - with placeholder', value: 'find . -name "*.txt" | xargs -I{} rm {}', description: 'Remove each .txt file found' },
    { key: 'xargs - one arg at a time', value: 'echo "a b c" | xargs -n1 echo', description: 'Process one argument per line' },
    { key: 'curl - GET request', value: 'curl https://api.example.com/users', description: 'Simple GET request' },
    { key: 'curl - POST JSON', value: "curl -X POST -H 'Content-Type: application/json' -d '{\"name\":\"test\"}' https://api.example.com", description: 'POST JSON data' },
    { key: 'curl - with auth token', value: 'curl -H "Authorization: Bearer $TOKEN" https://api.example.com', description: 'GET with Bearer token' },
    { key: 'curl - show headers only', value: 'curl -I https://example.com', description: 'Show response headers only' },
    { key: 'curl - follow redirects', value: 'curl -L https://example.com', description: 'Follow HTTP redirects' },
    { key: 'jq - extract key', value: 'curl -s api.com | jq ".data"', description: 'Extract "data" key from JSON' },
    { key: 'jq - multiple keys', value: 'curl -s api.com | jq "{name: .name, id: .id}"', description: 'Extract multiple keys as object' },
    { key: 'jq - filter array', value: 'curl -s api.com | jq ".data[] | select(.active == true)"', description: 'Filter array items by condition' },
    { key: 'jq - map values', value: 'curl -s api.com | jq ".data | map(.name)"', description: 'Map array to just names' },
    { key: 'jq - count items', value: 'curl -s api.com | jq ".data | length"', description: 'Count items in array' },
    { key: 'jq - keys of object', value: 'curl -s api.com | jq "keys"', description: 'Get all keys of JSON object' },
    { key: 'chmod - 755', value: 'chmod 755 script.sh', description: 'rwxr-xr-x (owner: rwx, others: rx)' },
    { key: 'chmod - 644', value: 'chmod 644 file.txt', description: 'rw-r--r-- (owner: rw, others: r)' },
    { key: 'tar - create archive', value: 'tar -czf archive.tar.gz ./folder', description: 'Create compressed tar archive' },
    { key: 'tar - extract', value: 'tar -xzf archive.tar.gz', description: 'Extract tar.gz archive' },
    { key: 'zip - create', value: 'zip -r archive.zip ./folder', description: 'Create zip archive' },
    { key: 'unzip - extract', value: 'unzip archive.zip', description: 'Extract zip archive' },
    { key: 'ps - all processes', value: 'ps aux', description: 'List all running processes' },
    { key: 'ps - grep for process', value: 'ps aux | grep "node"', description: 'Find node processes' },
    { key: 'kill - by process name', value: 'pkill -f "node"', description: 'Kill all processes matching "node"' },
    { key: 'disk usage', value: 'df -h', description: 'Show disk space usage' },
    { key: 'directory size', value: 'du -sh ./folder', description: 'Show folder size' },
    { key: 'top processes', value: 'top -o %CPU', description: 'Show top processes by CPU' },
    { key: 'watch - repeat command', value: 'watch -n 5 df -h', description: 'Run df -h every 5 seconds' },
  ],
})
