import {
  asciiTableTool,
  base64Tool,
  bcryptTool,
  caseConverterTool,
  cidrTool,
  colorTool,
  cronTool,
  curlTool,
  dataFormatTool,
  dockerCliToComposeTool,
  dockerTool,
  eisenhowerTool,
  fileOpsTool,
  gitTool,
  htmlEntitiesTool,
  httpStatusTool,
  jqTool,
  jwtDecoderTool,
  kubectlTool,
  loremTool,
  md5Tool,
  mermaidTool,
  mimeTypesTool,
  npmTool,
  permissionTool,
  portTool,
  postgresqlTool,
  regexTool,
  sha256Tool,
  sshTool,
  stringEscapeTool,
  systemTool,
  tailwindTool,
  textProcessTool,
  timestampTool,
  upperCaseTool,
  urlEscapeTool,
  uuidTool,
} from '.'
import { registry } from '@/lib/tools/registry'

registry.register(base64Tool)
registry.register(md5Tool)
registry.register(sha256Tool)
registry.register(bcryptTool)
registry.register(upperCaseTool)
registry.register(loremTool)
registry.register(uuidTool)
registry.register(dataFormatTool)
registry.register(dockerCliToComposeTool)
registry.register(caseConverterTool)
registry.register(jwtDecoderTool)
registry.register(colorTool)
registry.register(cronTool)
registry.register(permissionTool)
registry.register(timestampTool)
registry.register(portTool)
registry.register(mermaidTool)
registry.register(regexTool)
registry.register(textProcessTool)
registry.register(fileOpsTool)
registry.register(curlTool)
registry.register(jqTool)
registry.register(stringEscapeTool)
registry.register(systemTool)
registry.register(httpStatusTool)
registry.register(urlEscapeTool)
registry.register(postgresqlTool)
registry.register(gitTool)
registry.register(dockerTool)
registry.register(npmTool)
registry.register(kubectlTool)
registry.register(sshTool)
registry.register(mimeTypesTool)
registry.register(htmlEntitiesTool)
registry.register(asciiTableTool)
registry.register(tailwindTool)
registry.register(cidrTool)
registry.register(eisenhowerTool)

export { registry }
