/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppLayoutRouteRouteImport } from './routes/_appLayout/route'
import { Route as AppLayoutIndexRouteImport } from './routes/_appLayout/index'
import { Route as AppLayoutHomeRouteImport } from './routes/_appLayout/home'
import { Route as AppLayoutToolToolIdRouteImport } from './routes/_appLayout/tool/$toolId'

const AppLayoutRouteRoute = AppLayoutRouteRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutHomeRoute = AppLayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutToolToolIdRoute = AppLayoutToolToolIdRouteImport.update({
  id: '/tool/$toolId',
  path: '/tool/$toolId',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/home': typeof AppLayoutHomeRoute
  '/': typeof AppLayoutIndexRoute
  '/tool/$toolId': typeof AppLayoutToolToolIdRoute
}
export interface FileRoutesByTo {
  '/home': typeof AppLayoutHomeRoute
  '/': typeof AppLayoutIndexRoute
  '/tool/$toolId': typeof AppLayoutToolToolIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appLayout': typeof AppLayoutRouteRouteWithChildren
  '/_appLayout/home': typeof AppLayoutHomeRoute
  '/_appLayout/': typeof AppLayoutIndexRoute
  '/_appLayout/tool/$toolId': typeof AppLayoutToolToolIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/home' | '/' | '/tool/$toolId'
  fileRoutesByTo: FileRoutesByTo
  to: '/home' | '/' | '/tool/$toolId'
  id:
    | '__root__'
    | '/_appLayout'
    | '/_appLayout/home'
    | '/_appLayout/'
    | '/_appLayout/tool/$toolId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppLayoutRouteRoute: typeof AppLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/': {
      id: '/_appLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/home': {
      id: '/_appLayout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppLayoutHomeRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/tool/$toolId': {
      id: '/_appLayout/tool/$toolId'
      path: '/tool/$toolId'
      fullPath: '/tool/$toolId'
      preLoaderRoute: typeof AppLayoutToolToolIdRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
  }
}

interface AppLayoutRouteRouteChildren {
  AppLayoutHomeRoute: typeof AppLayoutHomeRoute
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutToolToolIdRoute: typeof AppLayoutToolToolIdRoute
}

const AppLayoutRouteRouteChildren: AppLayoutRouteRouteChildren = {
  AppLayoutHomeRoute: AppLayoutHomeRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutToolToolIdRoute: AppLayoutToolToolIdRoute,
}

const AppLayoutRouteRouteWithChildren = AppLayoutRouteRoute._addFileChildren(
  AppLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppLayoutRouteRoute: AppLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
